services:
  - type: web
    name: yojna-drishti
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node server/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
